### ISSUE TITLE
Script d'auto destruction des annonces

### ISSUE THREAD

**Issue by Emile-Filteau** [Emile-Filteau/LivrETS#16]
À chaque jour, le script détruit les annonces non-activés dans le système pour diminuer la charge sur le base de données

**Comment by mbinette91** [comment]
C'est fait (branche rake_cleanup_books). Je te laisse paramétrer le temps et ajouter la tâche dans les jobs récurrentes. 

Tu veux logger les livres supprimés?

**Comment by Emile-Filteau** [comment]
Looks good to me! Je merge sur le master et je vais configurer la task pour qu'elle soit daily sur Heroku
